#!/usr/bin/perl -wT -CSDA
use v5.14;

use App::MusicExpo;

App::MusicExpo->run;

__END__

=head1 NAME

musicexpo - script which generates a HTML table of music tags

=head1 SYNOPSIS

    # Creates a table with the songs a.mp3 and b.flac using the template 'index.tmpl' and caching the tags in the file 'cache.db'. The download links point to /music/a.mp3 and /music/b.mp3
    musicexpo a.mp3 b.flac

    # Disables caching, and the download links point to /download/a.flac, /download/b.flac, /download/c.flac
    musicexpo --no-caching --prefix /download/ my/music/a.flac my/music/b.flac othermusic/c.flac

    # Caches into /tmp/musicexpocache and uses directory/file.tmpl as template
    musicexpo --cache /tmp/musicexpocache --template directory/file.tmpl my-music/*.mp3

=head1 DESCRIPTION

musicexpo creates a HTML table from a list of songs.

The default template looks like:

    | Title   | Artist  | Album           | Genre   | Track | Year | Type |
    |---------+---------+-----------------+---------+-------+------+------|
    | Cellule | Silence | L'autre endroit | Electro | 01/09 | 2005 | FLAC |

where the title is a download link.

=head1 OPTIONS

=over

=item B<--template> I<template>

Path to the HTML::Template::Compiled template used for generating the music table. Defaults to 'index.tmpl'.

=item B<--prefix> I<prefix>

Prefix for download links. Defaults to '/music/'.

=item B<--cache> I<filename>

Path to the cache file. Created if it does not exist. Defaults to 'cache.db'

=item B<--caching>, B<--no-caching>

Enables or disables caching. Defaults to B<--caching>

=back

=head1 AUTHOR

Marius Gavrilescu, E<lt>marius@ieval.roE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2013 by Marius Gavrilescu

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.14.2 or,
at your option, any later version of Perl 5 you may have available.

